version: '2'

services:
  http-service:
    build:
      context: ./http-service/
    expose:
      - "9000"
  nginx-proxy:
    image: nginx:stable
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - "80"

  haproxy:
    # image: haproxy:1.6.5
    build:
      context: ./haproxy/
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    # ºcommand: bash -c "sleep 3 ; strace /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -d"
    command: bash -c "sleep 3 ; /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -d"
    ports:
      - "8000:80"
    security_opt:
      - seccomp:unconfined



